[package]
name = "blender-midi"
version = "0.1.0"
edition = "2021"

[dependencies]
rainout = { path = "deps/rainout", features = ["midi","jack-linux"]}
clap = "4.1.8"
log = "*"
simple_logger = "2.1"
thiserror = "1.0.39"

# [dev-dependencies]
# log = "*"
# simple_logger = "2.1"
